[tool.poetry]
name = "sundew"
version = "0.0.0"
description = ""
authors = ["devenjarvis <devenjarvis@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^1.10.2"
typer = {version = "^0.7.0", extras = ["all"]}


[tool.poetry.group.dev.dependencies]
mypy = "*"
black = "*"
ruff = "*"
poethepoet = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
fix = "ruff . --fix"
format = "black ."
lint = "ruff ."
test_examples = "python -m sundew ./examples"
test_sundew = "python -m sundew ./tests"
type = "mypy ."


[tool.ruff]
line-length = 100
select = ["ALL"]
ignore = ["D", "T", "ISC", "S101", "ANN101"]

