[tool.poetry]
name = "shore"
version = "0.1.0"
description = ""
authors = ["devenjarvis <devenjarvis@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.7.0"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^22.12.0"
ruff = "^0.0.196"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
